classDiagram
    class CourseController
    class ICourseService 
    class ICourseRepository
    CourseController ..> ICourseService
    ICourseService ..> ICourseRepository

    
    %% class EnrollmentController
    %% EnrollmentController ..> IEnrollmentService
    class IEnrollmentService {
        import_students_from_csv(course_id, file)
    }
    class IEnrollmentRepository
    IEnrollmentService ..> IEnrollmentRepository
    IEnrollmentService ..> IStudentRepository
    IEnrollmentService ..> ICourseRepository

    %% class StudentController
    %% class IStudentService {
    %%     import_github_usernames(file)
    %% }
    %% class IStudentRepository
    %% IStudentService ..> IStudentRepository
    %% StudentController ..> IStudentService

    class IGitHubService {
        import_github_names(course_id, file)
    }
    IGitHubService ..> IStudentRepository